knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            aws_s3:
                service_id: aws.s3.client
                bucket_name: '%env(AWS_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: images
    filesystems:
        image_fs:
            adapter: image_adapter
