vich_uploader:
    db_driver: orm
    storage: gaufrette
    mappings:
        image:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_BUCKET_NAME)%/images"
            upload_destination: image_fs
            delete_on_update: false
            delete_on_remove: false
